#!/usr/bin/env python3
"""Persist multi-agent workflow output to docs/research/, with a leak gate.

This repository is PUBLIC. Agent reports routinely contain host addresses,
hardware identifiers, and quotes from private repositories. Anything matching
SENSITIVE, or named in PRIVATE_SECTIONS, is written to .private/ (gitignored)
instead of docs/research/.

Usage:  python3 scripts/persist_workflow.py <journal.jsonl>
"""
import json
import re
import sys
from pathlib import Path

# Sections never published, regardless of scan result.
PRIVATE_SECTIONS = {"recon:infra-and-data", "recon:adjacent-repos"}

# A hit in a would-be-public section diverts it to .private/ and reports why.
SENSITIVE = {
    "tailnet address": re.compile(r"\b100\.(?:6[4-9]|[7-9]\d|1[01]\d|12[0-7])\.\d{1,3}\.\d{1,3}\b"),
    "private LAN address": re.compile(r"\b(?:192\.168|10)\.\d{1,3}\.\d{1,3}\.\d{1,3}\b"),
    "MAC address": re.compile(r"\b(?:[0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}\b"),
    "tailnet domain": re.compile(r"\b[\w-]+\.ts\.net\b"),
    "personal email": re.compile(r"[\w.+-]+@(?:gmail|outlook|yahoo|icloud)\.com"),
    "private repo internals": re.compile(r"\b(?:audiomem|moros|gotham|nexus|soul|hexguard)\b"),
}


def scan(text: str) -> dict[str, int]:
    return {name: len(set(p.findall(text))) for name, p in SENSITIVE.items() if p.search(text)}


def render(label: str, result: dict, run: str, date: str) -> str:
    out = [f"# {label}", ""]
    out.append(f"> Auto-generated by multi-agent workflow `{run}` on {date}.")
    out.append(f"> Agent label: `{label}`.")
    out.append("")
    out.append(result.get("report") or result.get("proposal") or json.dumps(result, indent=2))
    for field, heading in (("hard_facts", "Verified hard facts"),
                           ("open_questions", "Open questions"),
                           ("phases", "Phases"),
                           ("kill_criteria", "Kill criteria"),
                           ("load_bearing_claims", "Load-bearing claims")):
        items = result.get(field)
        if items:
            out += ["", "---", "", f"## {heading}", ""] + [f"- {i}" for i in items]
    return "\n".join(out) + "\n"


def main() -> int:
    journal = Path(sys.argv[1] if len(sys.argv) > 1 else "journal.jsonl")
    root = Path(__file__).resolve().parent.parent
    run, date = journal.parent.name, __import__("datetime").date.today().isoformat()

    labels: dict[str, str] = {}
    sections: dict[str, dict] = {}
    for line in journal.read_text().splitlines():
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        if d.get("type") == "started" and d.get("agentId"):
            labels[d["agentId"]] = d.get("label", d["agentId"])
        elif d.get("type") == "result" and isinstance(d.get("result"), dict):
            sections[labels.get(d.get("agentId"), d.get("agentId", "unknown"))] = d["result"]

    published = withheld = 0
    for label, result in sorted(sections.items()):
        body = render(label, result, run, date)
        hits = scan(body)
        private = label in PRIVATE_SECTIONS or bool(hits)
        target = root / (".private/research" if private else "docs/research")
        target.mkdir(parents=True, exist_ok=True)
        # Keep this repo's own paths readable; never leak the home directory.
        (target / f"{label.replace(':', '-')}.md").write_text(body.replace(str(Path.home()), "~"))
        if private:
            withheld += 1
            why = "listed private" if label in PRIVATE_SECTIONS else ", ".join(hits)
            print(f"  WITHHELD  {label:<36} ({why})")
        else:
            published += 1
            print(f"  published {label}")

    print(f"\n{published} published, {withheld} withheld to .private/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
